version: "3.8"
name: aims

services:
  college-db:
    image: mysql:latest
    container_name: college_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=college
      - MYSQL_USER=aims
      - MYSQL_PASSWORD=aims
    ports:
      - "3308:3306"
    volumes:
      - college_db_data:/var/lib/mysql

  college-ms:
    build: .
    image: aims_college_ms
    container_name: college_ms
    depends_on:
      - college-db
    links:
      - college-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://college-db:3306/college
      - SPRING_DATASOURCE_USERNAME=aims
      - SPRING_DATASOURCE_PASSWORD=aims
    ports:
      - "8082:8080"

volumes:
  college_db_data:
